In [7]:
import sys
print(sys.executable)

D:\Study\learning-python\.venv\Scripts\python.exe


In [2]:
import numpy as np
import matplotlib.pyplot as plt

# 如果需要画图
%matplotlib inline

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

AB = A @ B
print(AB)

[[ 58  64]
 [139 154]]


In [4]:
AB_manual = np.zeros((A.shape[0], B.shape[1]))
for i in range(A.shape[0]):
    for j in range(B.shape[1]):
        for k in range(A.shape[1]):
            AB_manual[i][j] += A[i][k] * B[k][j]

print(AB_manual)
print("一致:", np.allclose(AB, AB_manual))

[[ 58.  64.]
 [139. 154.]]
一致: True


In [8]:
BA = B @ A
print("A @ B 形状:", AB.shape)
print("B @ A 形状:", BA.shape)
print(BA)

A @ B 形状: (2, 2)
B @ A 形状: (3, 3)
[[ 39  54  69]
 [ 49  68  87]
 [ 59  82 105]]


In [5]:
M = np.array([[4, 1], [2, 3]])
eigvals, eigvecs = np.linalg.eig(M)
print("特征值:", eigvals)
print("特征向量:", eigvecs)

特征值: [5.+0.j 2.+0.j]
特征向量: [[ 0.70710678+0.j -0.4472136 +0.j]
 [ 0.70710678+0.j  0.89442719+0.j]]


In [6]:
for i in range(len(eigvals)):
    v = eigvecs[:, i]
    lam = eigvals[i]
    lhs = M @ v
    rhs = lam * v
    print(f"λ{i} = {lam}")
    print(f"  M@v = {lhs}")
    print(f"  λv  = {rhs}")
    print(f"  相等: {np.allclose(lhs, rhs)}")

λ0 = (5+0j)
  M@v = [3.53553391+0.j 3.53553391+0.j]
  λv  = [3.53553391+0.j 3.53553391+0.j]
  相等: True
λ1 = (2+0j)
  M@v = [-0.89442719+0.j  1.78885438+0.j]
  λv  = [-0.89442719+0.j  1.78885438+0.j]
  相等: True


In [9]:
np.random.seed(42)
A3 = np.random.randn(3, 3)
b3 = np.random.randn(3)

print("A3 =")
print(A3)
print("b3 =", b3)

x = np.linalg.solve(A3, b3)
print("\n解 x =", x)
print("验证 A3 @ x =", A3 @ x)
print("是否等于 b3:", np.allclose(A3 @ x, b3))

A3 =
[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]
b3 = [ 0.54256004 -0.46341769 -0.46572975]

解 x = [-0.11791536  0.23412342  0.97809541]
验证 A3 @ x = [ 0.54256004 -0.46341769 -0.46572975]
是否等于 b3: True


In [10]:
x_inv = np.linalg.inv(A3) @ b3
print("用求逆解 x =", x_inv)
print("和 solve 结果是否一致:", np.allclose(x, x_inv))

用求逆解 x = [-0.11791536  0.23412342  0.97809541]
和 solve 结果是否一致: True
